language: R
sudo: false
cache: packages
dist: trusty

env:
  global:
  - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"

notifications:
  email: false

before_install:
    - sudo apt-get install --yes udunits-bin libproj-dev libgeos-dev libgdal-dev libgdal1-dev libudunits2-dev

before_install:
  - R -e 'install.packages("devtools")'
  - R -e 'devtools::install_github("pbiecek/DALEX")'
  - R -e 'devtools::install_github("ModelOriented/DALEX2")'

r_packages:
  - archivist
  - ggplot2
  - covr
  - nnet
  - randomForest
  - e1071
  - caret

after_success:
  - Rscript -e 'library(covr); codecov()'
