language: R
sudo: false
cache: packages
dist: trusty
env:
  global:
  - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
notifications:
  email: false
r_packages:
  - archivist
  - ggplot2
  - DALEX
  - covr
install:
- R -e 'devtools::install_github("ModelOriented/DALEX2")'


after_success:
  - Rscript -e 'library(covr); codecov()'
